Initial go at converting to fedora-messaging
fedora-infra/datanommer pull request #155
Opened 2021-07-19 13:42 UTC by ryanlerch

Signed-off-by: Ryan Lerch <rlerch@redhat.com>

2021-07-19 14:46 UTC, abompard commented
Oops I didn't see that your PR created the database, so I did it too and pushed my commit. Sorry about that. Could you rebase to pick it up?

2021-07-19 19:48 UTC, ryanlerch commented
> Oops I didn't see that your PR created the database, so I did it too and pushed my commit. Sorry about that. Could you rebase to pick it up?

no worries -- glad that i almost got that part right :) 

it looks better split out into a seperate task file tho.

2021-07-19 20:01 UTC, ryanlerch commented
rebased to your changes! will work on finishing this off and doing tests today.

2021-07-19 20:17 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +    datanommer_sqlalchemy_url = fedora_messaging_config.conf["consumer_config"][
I'd rather make this check at the beginning of the commands, this way we can mock the configuration more easily in tests.

2021-07-19 20:18 UTC, abompard commented on datanommer.consumer/datanommer/consumer/__init__.py
> +config.conf.setup_logging()
Is it needed when run with `fedora-messaging consume`?

2021-07-19 20:19 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +    #       but to get it working, just return empty for each of these
It would be `message.usernames` and `message.packages` I think.

2021-07-22 08:28 UTC, ryanlerch commented
Resolves #132

2021-07-22 16:02 UTC, abompard requested changes
Quite a few comments! :-)

Please also convert the testing helpers in `datanommer.models.testing`, you can replace the `fedmsg_config` fixture with something like: 
```python
@pytest.fixture()
def datanommer_db_url(pgsql):
    return (
        f"postgresql+psycopg2://{pgsql.info.user}:@"
        f"{pgsql.info.host}:{pgsql.info.port}"
        f"/{pgsql.info.dbname}"
    )
```
Then you can use that in the `datanommer_models` fixture below.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +        raise ValueError(
A [ClickException](https://click.palletsprojects.com/en/7.x/exceptions/) would be more appropriate here I think.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +        f"Creating Datanommer database and tables at {datanommer_sqlalchemy_url}"
This is going to print the database password on standard output, I don't think we should do that.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +        query = query.filter(m.Message.timestamp <= before)
Don't we need to convert `before` and `after` to datetime objects? I would be surprised that SQLAlchemy do it automatically. Anyway in that case we need to make sure the input is in an acceptable datetime format, I think converting to a datetime object beforehand and catching the exception if it fails would be a better course of action.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +        categories = [
This could be replaced by a database query, to list all categories currently in the database, like a `SELECT DISTINCT category FROM messages`.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
>  from fedmsg.encoding import pretty_dumps
This should be dropped.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +    click.echo(pretty_dumps(query.all()))
`pretty_dumps` still comes from fedmsg.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/datanommer/commands/__init__.py
> +    a_year = timedelta(days=365)
Oh yeah? What about leap years?... (just kidding)

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/pyproject.toml
>  fedmsg = "^1.1.2"
This should be dropped.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/tests/test_commands.py
> +def get_url(mocker):
It's a bit of a weird name, no? It's called `get_*` but does not return anything.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/tests/test_commands.py
> +    # mocked_config["before"] = "2013-02-16"
You can probably remove that.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/tests/test_commands.py
> +    print(f"asdasd{result.output}")
Looks like forgotten debug code

2021-07-22 16:02 UTC, abompard commented on datanommer.consumer/pyproject.toml
>  fedmsg = "^1.1.2"
This should be dropped.

2021-07-22 16:02 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +def add_fedora_message(message):
Why make a new function? Why not rewrite `add()`?

2021-07-22 16:02 UTC, abompard commented on datanommer.models/pyproject.toml
> +fedora-messaging = "^2.1.0"
fedmsg should be removed too.

2021-07-22 16:02 UTC, abompard commented on datanommer.commands/tests/test_commands.py
> +    mock_get_url.return_value = "sqlite:///fake.db"
This is actually entirely unnecessary, because once the models have been initialized, they abort any further attempts to initialize them again. And the `datanommer_models` fixture does it.

What would be a bit better, I think, would be to mock the `m.init()` call in the command, so that it's never actually run.

2021-07-22 16:02 UTC, abompard commented on datanommer.consumer/tests/test_consumer.py
> +    mock_get_url.return_value = "sqlite:///fake.db"
Same comment as above, the models can't be initialized twice and it's probably better to mock the call to `init()`.

2021-07-23 04:39 UTC, ryanlerch commented on datanommer.commands/tests/test_commands.py
> +    # mocked_config["before"] = "2013-02-16"
removed

2021-07-23 04:39 UTC, ryanlerch commented on datanommer.commands/tests/test_commands.py
> +    print(f"asdasd{result.output}")
removed

2021-07-23 04:40 UTC, ryanlerch commented on datanommer.models/datanommer/models/__init__.py
> +def add_fedora_message(message):
fixed

2021-07-23 04:41 UTC, ryanlerch commented on datanommer.commands/datanommer/commands/__init__.py
> +        query = query.filter(m.Message.timestamp <= before)
added checks

2021-07-23 05:47 UTC, ryanlerch commented on datanommer.commands/datanommer/commands/__init__.py
> +        categories = [
fixed

2021-07-23 09:02 UTC, abompard requested changes
More comments! :-)

2021-07-23 09:02 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +# def add(envelope):
You can remove the commented block, it'll make it easier to compare.

2021-07-23 09:02 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +    packages = message.packages
You don't really need to define the `usernames` and `packages` variables as they're only used once below and their definition is pretty simple.

2021-07-23 09:02 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
>      except IntegrityError:
Are you sure the only case where an `IntegrityError` can happen is when there's a duplicate ID? It seems a bit wide. Maybe look at the exception to make sure that's what's happenning, and print it if it's not.

2021-07-23 09:02 UTC, abompard commented on datanommer.models/tests/test_model.py
> -def test_add_missing_timestamp(datanommer_models):
This test is still relevant, let's keep it (with `send-at` instead of `timestamp`)

2021-07-23 09:02 UTC, abompard commented on datanommer.models/tests/test_model.py
> -def test_add_and_check_for_others(datanommer_models):
We'll want to keep this test, it's checking the `Message.get_array()` method.

2021-07-23 09:02 UTC, abompard commented on datanommer.models/tests/test_model.py
> -def test_add_headers(datanommer_models):
This may still be relevant, no?

2021-07-26 09:43 UTC, ryanlerch commented on datanommer.models/datanommer/models/__init__.py
>      except IntegrityError:
added a check to print errors for duplicate ids and for not

2021-07-26 12:56 UTC, ryanlerch commented
ok, most of the changes are complete 

the only thing i am hung up on is removing the pretty_dumps encoding of json from commands

@abompard when you are around again, i think i need a hand on this one

2021-07-27 08:32 UTC, abompard requested changes
Please also drop the files in the `fedmsg.d` directory at the root of the repo (and remove it from the `include` line in the `pyproject.toml` file there).

There's still a reference to `fedmsg` in `datanommer.models/alembic.ini`.

2021-07-27 08:32 UTC, abompard commented on datanommer.commands/pyproject.toml
>  fedmsg = "^1.1.2"
Additional note: the `fedmsg.d/*` line in the `include` list should also be removed.

2021-07-27 08:32 UTC, abompard commented on datanommer.consumer/pyproject.toml
> -fedmsg = "^1.1.2"
Please also remove the `fedmsg.d/*` line from the `include` list.

2021-07-27 08:32 UTC, abompard commented on datanommer.models/pyproject.toml
> -fedmsg = "^1.1.2"
Please also remove the `fedmsg.d/*` line from the `include` list.

2021-07-27 16:13 UTC, abompard requested changes

2021-07-27 16:13 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +        if "duplicate key value violates unique constraint" in str(e):
Unfortunately the error message is translated by PostgreSQL according to the user's locale, so this only works when the locale is English. I suggest using this test instead, which works independently from the locale:
```python
from psycopg2.errors import UniqueViolation
if isinstance(e.orig, UniqueViolation):
```

2021-07-27 16:13 UTC, abompard commented on datanommer.models/tests/test_model.py
> +    assert dbmsg.timestamp == datetime.datetime(2021, 7, 27, 4, 22, 42)
This fails on systems that are not at UTC, because the timestamps are stored as naive timestamps in the database. It's safer to compare aware timestamps, so I suggest the following:
```python
assert dbmsg.timestamp.astimezone(datetime.timezone.utc) == datetime.datetime(
        2021, 7, 27, 4, 22, 42, tzinfo=datetime.timezone.utc
    )
```

2021-07-27 19:55 UTC, ryanlerch commented
Thanks!

Have updated the commit with those 2 new changes

2021-07-28 04:47 UTC, abompard approved these changes
Looks good! Thanks for your work!
Now on to removing `pretty_dump` and `fedmsg` entirely ;-)

2021-07-28 04:48 UTC, merged