Towncrier config
fedora-infra/datanommer pull request #157
Opened 2021-07-23 13:33 UTC by james02135

2021-07-23 13:56 UTC, james02135 commented
WIP - addded towncrier config data to the pyproject.toml file and two files into the new "news" directory based on Noggin configuration.

2021-08-11 08:43 UTC, abompard requested changes
We should avoid having copies of things when we can, so let's share the `get-authors.py` script and the template. They could be in a subdirectory of `/tools` for example.

2021-08-16 14:29 UTC, StephenCoady requested changes

2021-08-16 14:29 UTC, StephenCoady commented on datanommer.commands/datanommer/commands/__init__.py
> +    import importlib.metadata  # pragma: no cover
You don't need to add `pragma: no cover` to every line, you can add it to branch points instead and then everything in that branch won't be counted.

2021-08-16 14:29 UTC, StephenCoady commented on datanommer.consumer/datanommer/consumer/__init__.py
> +    import importlib.metadata  # pragma: no cover
Same for this file.

2021-08-17 21:42 UTC, james02135 commented on datanommer.consumer/datanommer/consumer/__init__.py
> +    import importlib.metadata  # pragma: no cover
Should be all set

2021-08-18 08:36 UTC, StephenCoady approved these changes

2021-08-18 08:37 UTC, merged