fix the contains query so it works with jsonb
fedora-infra/datanommer pull request #245
Opened 2021-09-16 09:06 UTC by StephenCoady

I've tested this locally and it's working - but I'd like to test it in staging if possible.

The reason is that I'm not 100% sure of the `msg` json key. I can see it locally but I don't think it's in all messages.
Signed-off-by: Stephen Coady <scoady@redhat.com>

2021-09-16 09:51 UTC, abompard commented
Yeah we can't be sure the field has a `msg` key, I think newer fedora-messaging messages don't.

I found a way to extract the whole jsonb field to text for searching, but it uses the `#>>` operator, not the `json_extract_path_text()` function. If you can find a way to use it in SQLAlchemy I think it'll work. Example:
```
SELECT '{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}'::json #>> '{}';
```

In our case it would be `SELECT body #>> '{}' from messages`, I think.

Also, please reference #231 in your commit message.

2021-09-20 08:35 UTC, abompard requested changes

2021-09-20 08:35 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +            print(query)
Leftover?

2021-09-20 08:35 UTC, abompard commented on datanommer.models/datanommer/models/__init__.py
> +                    *(Message.msg.op("#>>")("{}").like(contain) for contain in contains)
So, we're not wrapping contain with percent signs anymore, should we restore that?

2021-09-20 09:20 UTC, abompard approved these changes

2021-09-20 09:22 UTC, abompard commented
Black is unhappy. You can add automatic pre-commit checks by running `pre-commit install` (install the `pre-commit` package if you don't have it yet, it's pretty cool).

2021-09-20 09:34 UTC, StephenCoady commented
thanks for the reviews :+1:

2021-09-20 09:37 UTC, merged